# Generated by Django 4.2 on 2023-07-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_picture_likes_alter_user_avatar_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='likes',
        ),
    ]
